models:
  yolo:
    path: "models/injury_detection_model/weights/best.pt"  # Use your trained 4-class model
    confidence_threshold: 0.25  # Lower threshold for better detection
    device: "gpu"  # can be "cpu" or "gpu"
    enhanced_mode: true  # Use enhanced detector for better results
    injury_classes:
      - male
      - female
      - injury
      - no injury
    age_group_classes:
      - age_0_20
      - age_21_40
      - age_41_60
      - age_61_plus
    gender_classes:
      - male
      - female

cloud:
  service: "firebase"
  credentials_path: "config/firebase_credentials.json"
  storage_bucket: "ai-accident-analysis.appspot.com"
  database_url: "https://ai-accident-analysis-default-rtdb.firebaseio.com"

camera:
  device_id: 1 # Using camera ID 2
  width: 1920 
  height: 1080
  fps: 30  # Reduced from 60 to improve performance

detection:
  confidence_threshold: 0.45
  save_detected_images: true
  save_path: "data/detected_images"